version: '3.8'

services:
  football-etl:
    build: .
    container_name: football_etl

    volumes:
      - ./data:/app/data  # Вот это связывает папки!
      - ./logs:/app/logs

    environment:
      - OUTPUT_PATH=/app/data/competitions.csv
    restart: "no"